config/routes.rb
Rails.application.routes.draw do



  resources :cart_items, only: [:index, :create, :update, :destroy] do
     collection do
       delete 'destroy_all'
    end
  end

  resources :deliveries, only: [:index, :create, :edit, :update, :destroy]


  devise_for :admins, controllers: {
    sessions: 'admin/admins/sessions',
    registrations: 'admin/admins/registrations',
    passwords: 'admin/admins/passwords'
  }

  namespace :admin do
  	resources :products, only: [:new, :create, :edit, :update, :show, :index]
  	get 'home/top'
  	root 'home#top'
    get 'search' => 'search#search'
  	resources :orders, only: [:update, :index, :show]
  	resources :order_items, only: [:update]
  	resources :genres, only: [:index, :create, :edit, :update]
    resources :clients, only: [:show, :edit, :update, :index] do
      member do
        get "unsubscribe"
        patch "unsubscribe"
      end
    end
  end

  scope module: :client do
    devise_for :clients, controllers: {
      sessions: 'client/clients/sessions',
      registrations: 'client/clients/registrations',
      passwords: 'client/clients/passwords'
    }
  	resources :products, only: [:index, :show]
  	get 'home/top'
  	root 'home#top'
  	get 'home/about'
  	resources :orders, only: [:new, :create, :index, :show]
  	post 'orders/confirm'
  	get 'orders/thanks'
    get 'products/search/:id' => 'products#search', as: 'products_search'
    resources :clients, only: [:show, :edit, :update] do
      member do
        get "unsubscribe"
        patch "unsubscribe"
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/clients_controller.rb
class Admin::ClientsController < ApplicationController

    before_action :authenticate_admin!

  def show
    @client = Client.find(params[:id])
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])
    if @client.update(client_params)
      redirect_to admin_client_path(@client)
    else
      render "edit"
    end
  end

  def index
    @clients = Client.all
  end

  private
    def client_params
      params.require(:client).permit(
        :last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postcode, :address, :phone_number, :is_deleted)
    end
end

app/controllers/client/clients/confirmations_controller 4.rb
# frozen_string_literal: true

class Client::Clients::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/client/clients/confirmations_controller.rb
# frozen_string_literal: true

class Client::Clients::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/client/clients/omniauth_callbacks_controller 4.rb
# frozen_string_literal: true

class Client::Clients::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/client/clients/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Client::Clients::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/client/clients/passwords_controller 4.rb
# frozen_string_literal: true

class Client::Clients::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/client/clients/passwords_controller.rb
# frozen_string_literal: true

class Client::Clients::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/client/clients/registrations_controller.rb
# frozen_string_literal: true

class Client::Clients::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/client/clients/sessions_controller.rb
# frozen_string_literal: true

class Client::Clients::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  before_action :reject_client, only: [:create]

  protected

  def reject_client
    @client = Client.find_by(email: params[:client][:email].downcase)
    if @client
      if (@client.valid_password?(params[:client][:password]) && (@client.active_for_authentication? == false))
        flash[:notice] = "退会済みです。有効会員になる場合は管理者までご連絡ください。"
        redirect_to new_client_session_path
      end
    else
      flash[:notice] = "必須項目を入力してください。"
    end
  end

end

app/controllers/client/clients/unlocks_controller 4.rb
# frozen_string_literal: true

class Client::Clients::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/client/clients/unlocks_controller.rb
# frozen_string_literal: true

class Client::Clients::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/client/clients_controller 2.rb
class Client::ClientsController < ApplicationController
  def show
    @client = Client.find(params[:id])
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])
    @client.update(client_params)
  end

  def unsubscribe
    @client = Client.find(params[:id])
    if request.patch?
      @client.update(is_deleted: true)
      redirect_to root_path
    end
  end

  private
    def client_params
      params.require(:client).permit(
        :last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postcode, :address, :phone_number)
    end
end

app/controllers/client/clients_controller.rb
class Client::ClientsController < ApplicationController

  before_action :authenticate

  def show
    @client = Client.find(params[:id])
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])
    if @client.update(client_params)
      redirect_to client_path(@client)
    else
      render "edit"
    end
  end

  def unsubscribe
    @client = Client.find(params[:id])
    if request.patch?
      @client.update(is_deleted: true)
      reset_session
      flash[:notice] = 'ご利用ありがとうございました。'
      redirect_to root_path
    end
  end

  private
    def client_params
      params.require(:client).permit(
        :last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postcode, :address, :phone_number, :is_deleted)
    end

    def correct_client
      client = Client.find(params[:id])
      if client.id != current_client.id
        redirect_to client_path(current_client)
      end
    end
    
    def authenticate
      unless client_signed_in?
        redirect_to new_client_session_url
        flash[:notice] = "ここから先はログインが必要です!!"
      end
    end
end

app/controllers/client/home_controller.rb
class Client::HomeController < ApplicationController
  def top
  	@genres  =Genre.all
  	@products = Product.all
  end

  def about
  end
end

app/controllers/client/orders_controller.rb
class Client::OrdersController < ApplicationController

  before_action :set_client
  before_action :authenticate

  def new
    @order = Order.new
  end

  def create
    if current_client.cart_items.exists?
      @order = Order.new(order_params)
      @order.client_id = current_client.id
      @add = params[:order][:add].to_i
      case @add
        when 1
          @order.postcode = @client.postcode
          @order.address = @client.address
          @order.name = "#{@client.last_name} #{@client.first_name}"
        when 2
          @order.postcode = params[:order][:postcode]
          @order.address = params[:order][:address]
          @order.name = params[:order][:name]
        when 3
          @order.postcode = params[:order][:postcode]
          @order.address = params[:order][:address]
          @order.name = params[:order][:name]
      end
      @order.save

      unless Delivery.find_by(address: @order.address)
        @delivery = Delivery.new
        @delivery.postcode = @order.postcode
        @delivery.address = @order.address
        @delivery.name = @order.name
        @delivery.client_id = current_client.id
        @delivery.save
      end

      current_client.cart_items.each do |cart_item|
        order_item = @order.order_items.build
        order_item.order_id = @order.id
        order_item.product_id = cart_item.product_id
        order_item.quantity = cart_item.quantity
        order_item.price = cart_item.product.price
        order_item.save
        cart_item.destroy
      end
      render :thanks
    else
      flash[:notice] = "カートが空です！"
      redirect_to root_path
    end
  end

  def confirm
    @order = Order.new
    @cart_items = current_client.cart_items
    @order.pay_method = params[:order][:pay_method]
    @order.billed_amount = params[:order][:billed_amount]
    @add = params[:order][:add].to_i
    case @add
      when 1
        @order.postcode = @client.postcode
        @order.address = @client.address
        @order.name = "#{@client.last_name} #{@client.first_name}"
      when 2
        @address = params[:order][:address].to_i
        @delivery = Delivery.find(@address)
        @order.postcode = @delivery.postcode
        @order.address = @delivery.address
        @order.name = @delivery.name
      when 3
        @order.postcode = params[:order][:new_add][:postcode]
        @order.address = params[:order][:new_add][:address]
        @order.name = params[:order][:new_add][:name]
    end
  end

  def thanks
  end

  def index
    @orders = @client.orders.order(id: "DESC")
  end

  def show
    @order = Order.find(params[:id])
    if @order.client_id != current_client.id
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def set_client
    @client = current_client
  end

  def order_params
    params.require(:order).permit(
      :address, :name, :status, :pay_method, :postcode, :freight, :billed_amount,
      order_items_attributes: [:order_id, :product_id, :quantity, :price, :production_status]
      )
  end

  def authenticate
    unless client_signed_in?
      redirect_to new_client_session_url
      flash[:notice] = "ここから先はログインが必要です!!"
    end
  end
end

app/controllers/client/products_controller.rb
class Client::ProductsController < ApplicationController

  before_action :correct_product, only: [:show]
  before_action :correct_genre, only: [:search]

  def index
    @products = Product.joins(:genre).where(genres: {valid_flag: true}).page(params[:page]).per(8)
    @genres = Genre.all
  end

  def show
  	@cart_item = CartItem.new
    @genres = Genre.all
  end

  def search
    @products = @genre.products.page(params[:page]).per(8)
    @genres = Genre.all
  end

  private
  def correct_product
    @product = Product.find(params[:id])
    if @product.genre.valid_flag == false
      redirect_to products_path
    end
  end

  def correct_genre
    @genre = Genre.find(params[:id])
    if @genre.valid_flag == false
      redirect_to products_path
    end
  end

end

app/helpers/admin/clients_helper.rb
module Admin::ClientsHelper
end

app/helpers/client/clients_helper 2.rb
module Client::ClientsHelper
end

app/helpers/client/clients_helper.rb
module Client::ClientsHelper
end

app/views/admin/clients/edit.html 2.erb
<h2><%= @client.last_name %><%= @client.first_name %>さんの会員情報編集</h2>

  <div class="field">
    会員ID
    <%= @client.id %>
  </div>

<%= form_for(@client) do |f| %>

 <div class="field">
    <%= f.label :名前 %>
    <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name" %>
    <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name" %>
  </div>

  <div class="field">
    <%= f.label :フリガナ %>
    <%= f.text_field :last_name_kana, autofocus: true, autocomplete: "last_name_kana" %>
    <%= f.text_field :first_name_kana, autofocus: true, autocomplete: "first_name_kana" %>
  </div>

  <div class="field">
    <%= f.label :郵便番号（ハイフンなし） %>
    <%= f.text_field :postcode, autofocus: true, autocomplete: "postcode" %>
  </div>

  <div class="field">
    <%= f.label :住所 %>
    <%= f.text_field :address, autofocus: true, autocomplete: "address" %>
  </div>

  <div class="field">
    <%= f.label :電話番号（ハイフンなし） %>
    <%= f.text_field :phone_number, autofocus: true, autocomplete: "phone_number" %>
  </div>

  <div class="field">
    <%= f.label :メールアドレス %>
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :会員ステータス %>
    <%= f.radio_button :is_deleted, true %>有効
    <%= f.radio_button :is_deleted, false %>無効
  </div>

  <div class="actions">
    <%= f.submit "変更を保存する" %>
  </div>

<% end %>

app/views/admin/clients/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-mt-2">
    <h2><%= @client.last_name %><%= @client.first_name %>さんの会員情報編集</h2>
      <% if @client.errors.any? %>
        <div class="alert alert-danger">
          <h4><%= @client.errors.count %>件のエラーがあります。</h4>
          <ul>
            <% @client.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>


<%= form_for @client,:url => {controller: "clients", action: "update"} do |f| %>
<table>
  <tr>
    <td scop="col">会員ID</td>
    <td scop="col"><%= @client.id %></td>
    <td colspan="1"></td>
  </tr>
  <tr>
    <td><%= f.label :名前 %></td>
    <td><%= f.text_field :last_name, autofocus: true, autocomplete: "last_name" %></td>
    <td><%= f.text_field :first_name, autofocus: true, autocomplete: "first_name" %></td>
   
  </tr>
  <tr>
    <td><%= f.label :フリガナ %></td>
    <td><%= f.text_field :last_name_kana, autofocus: true, autocomplete: "last_name_kana" %></td>
    <td><%= f.text_field :first_name_kana, autofocus: true, autocomplete: "first_name_kana" %></td>

  </tr>
  <tr>
    <td><%= f.label :郵便番号（ハイフンなし） %></td>
    <td><%= f.text_field :postcode, autofocus: true, autocomplete: "postcode" %></td>
    <td colspan="1"></td>
  </tr>
  <tr>
    <td><%= f.label :住所 %></td>
    <td colspan="2"><%= f.text_field :address, autofocus: true, autocomplete: "address", class: "hogehoge", size: "60x50" %></td>
  </tr>
  <tr>
    <td><%= f.label :電話番号（ハイフンなし） %></td>
    <td><%= f.text_field :phone_number, autofocus: true, autocomplete: "phone_number" %></td>
    <td colspan="1"></td>
  </tr>
  <tr>
    <td><%= f.label :メールアドレス %></td>
    <td><%= f.email_field :email, autofocus: true, autocomplete: "email" %></td>
    <td colspan="1"></td>
  </tr>
  <tr>
    <td><%= f.label :会員ステータス %></td>
    <td><%= f.radio_button :is_deleted, "false" %>有効
        <%= f.radio_button :is_deleted, "true" %>退会済み</td>
  </tr>
</table>

  <div class="actions">
    <%= f.submit "変更を保存する", class: "btn btn-primary" %>
  </div>
<% end %>
</div>
</div>
</div>

app/views/admin/clients/index.html 2.erb
<h2>会員一覧</h2>

<table border="1">
	<thead>
		<tr bgcolor="gray">
			<th>会員ID</th>
			<th>氏名</th>
			<th>メールアドレス</th>
			<th>ステータス</th>
		</tr>
	</thead>
	<% @clients.each do |client| %>
		<tbody>
			<tr>
				<td><%= client.id %></td>
				<td><%= link_to client.last_name, admin_client_path(client) %><%= client.first_name %></td>
				<td><%= client.email %></td>
				<td><% if client.is_deleted == true %>有効
	                <% else %>退会済み
	                <% end %>
				</td>
			</tr>
		</tbody>
	<% end %>
</table>

app/views/admin/clients/index.html.erb
<div class="container">
	<div class="row">
	    <div class="col-xs-1">
	    </div>
	    <div class="col-xs-9">
			<h2>会員一覧</h2>
			 <table class="api-table">
			<thead>
				<tr>
					<th class="api-th">会員ID</th>
					<th class="api-th">氏名</th>
					<th class="api-th">メールアドレス</th>
					<th class="api-th">ステータス</th>
				</tr>
			</thead>
			<% @clients.each do |client| %>
				<tbody>
					<tr>
						<td class="api-td"><%= client.id %></td>
						<td class="api-td"><%= link_to admin_client_path(client) do %>
								<%= client.last_name %><%= client.first_name %>
								<% end %></td>
						<td class="api-td"><%= client.email %></td>
						<td class="api-td"><% if client.is_deleted == true %>退会済み
								<% else %>有効
								<% end %></td>
					</tr>
				</tbody>
			<% end %>
		</table>
	</div>

</div>

app/views/admin/clients/show.html 2.erb
<h2><%= @client.last_name %><%= @client.first_name %>さんの会員詳細</h2>

<table border="1">
    <tr>
      <td>顧客ID</td>
      <td><%= @client.id %>
        <% if @client.is_deleted == true %>有効会員
        <% else %>退会済み
        <% end %>
      </td>
    </tr>
    <tr>
      <td>氏名</td>
      <td><%= @client.last_name %> <%= @client.first_name %></td>
    </tr>
    <tr>
      <td>カナ</td>
      <td><%= @client.last_name_kana %> <%= @client.first_name_kana %></td>
    </tr>
    <tr>
      <td>郵便番号</td>
      <td><%= @client.postcode %></td>
    </tr>
    <tr>
      <td>住所</td>
      <td><%= @client.address %></td>
    </tr>
    <tr>
      <td>電話番号</td>
      <td><%= @client.phone_number %></td>
    </tr>
    <tr>
      <td>メールアドレス</td>
      <td><%= @client.email %></td>
    </tr>
</table>

  <table>
    <tr>
      <td>
      <%= link_to '編集する', edit_client_path, class: "btn btn-primary" %>
      </td>
      <td><h4>注文履歴</h4></td>
      <td><%= link_to '一覧を見る', orders_path, class: "btn btn-primary" %></td>
    </tr>
  </table>
  

app/views/admin/clients/show.html.erb
<div class="container">
  <div class="row">
    <h2><%= @client.last_name %><%= @client.first_name %>さんの会員詳細</h2>
      <table>
          <tr>
            <td>顧客ID</td>
            <td><%= @client.id %>
              <% if @client.is_deleted == true %><span class="label label-info">退会済み</span>
              <% else %><span class="label label-info">有効会員</span>
              <% end %>
            </td>
          </tr>
          <tr>
            <td>氏名</td>
            <td><%= @client.last_name %> <%= @client.first_name %></td>
          </tr>
          <tr>
            <td>カナ</td>
            <td><%= @client.last_name_kana %> <%= @client.first_name_kana %></td>
          </tr>
          <tr>
            <td>郵便番号</td>
            <td><%= @client.postcode %></td>
          </tr>
          <tr>
            <td>住所</td>
            <td><%= @client.address %></td>
          </tr>
          <tr>
            <td>電話番号</td>
            <td><%= @client.phone_number %></td>
          </tr>
          <tr>
            <td>メールアドレス</td>
            <td><%= @client.email %></td>
          </tr>
      </table>
  </div>
  <div class="row">
    <div class="col-mt-2">
      <table>
        <tr>
          <td><%= link_to '編集する', edit_admin_client_path, class: "btn btn-primary" %></td>
          <td><%= link_to '注文履歴一覧を見る', admin_orders_path, class: "btn btn-primary" %></td>
        </tr>
      </table>
    </div>
  </div>
</div>