config/routes.rb
Rails.application.routes.draw do



  resources :cart_items, only: [:index, :create, :update, :destroy] do
     collection do
       delete 'destroy_all'
    end
  end

  resources :deliveries, only: [:index, :create, :edit, :update, :destroy]


  devise_for :admins, controllers: {
    sessions: 'admin/admins/sessions',
    registrations: 'admin/admins/registrations',
    passwords: 'admin/admins/passwords'
  }

  namespace :admin do
  	resources :products, only: [:new, :create, :edit, :update, :show, :index]
  	get 'home/top'
  	root 'home#top'
    get 'search' => 'search#search'
  	resources :orders, only: [:update, :index, :show]
  	resources :order_items, only: [:update]
  	resources :genres, only: [:index, :create, :edit, :update]
    resources :clients, only: [:show, :edit, :update, :index] do
      member do
        get "unsubscribe"
        patch "unsubscribe"
      end
    end
  end

  scope module: :client do
    devise_for :clients, controllers: {
      sessions: 'client/clients/sessions',
      registrations: 'client/clients/registrations',
      passwords: 'client/clients/passwords'
    }
  	resources :products, only: [:index, :show]
  	get 'home/top'
  	root 'home#top'
  	get 'home/about'
  	resources :orders, only: [:new, :create, :index, :show]
  	post 'orders/confirm'
  	get 'orders/thanks'
    get 'products/search/:id' => 'products#search', as: 'products_search'
    resources :clients, only: [:show, :edit, :update] do
      member do
        get "unsubscribe"
        patch "unsubscribe"
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :client
	has_many :order_items, dependent: :destroy
	has_many :products, :through => :order_items
	accepts_nested_attributes_for :order_items

	enum pay_method: { クレジットカード: 0, 銀行振込: 1 }
	enum status: { 入金待ち: 0, 入金確認: 1, 制作中: 2, 発送準備中: 3, 発送済み: 4 }

	validates :postcode, length: {is:7}
	validates :address, :postcode, :name, presence: true
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

    before_action :authenticate_admin!
    PER = 10

  def index
  	@orders = Order.page(params[:page]).per(PER).order(id: "DESC")
  end

  def show
  	@order = Order.find(params[:id])
  	@order_items = @order.order_items
  end

  def update
  	@order = Order.find(params[:id])
    @order_items = @order.order_items
    if @order.update(order_params)
      if @order.status == "入金確認"
        @order_items.update(production_status: 1)
      end
    end
  	redirect_to admin_order_path(@order)
  end

  private
  def order_params
  	params.require(:order).permit(:status)
  end
end

app/controllers/client/orders_controller.rb
class Client::OrdersController < ApplicationController

  before_action :set_client
  before_action :authenticate

  def new
    @order = Order.new
  end

  def create
    if current_client.cart_items.exists?
      @order = Order.new(order_params)
      @order.client_id = current_client.id
      @add = params[:order][:add].to_i
      case @add
        when 1
          @order.postcode = @client.postcode
          @order.address = @client.address
          @order.name = "#{@client.last_name} #{@client.first_name}"
        when 2
          @order.postcode = params[:order][:postcode]
          @order.address = params[:order][:address]
          @order.name = params[:order][:name]
        when 3
          @order.postcode = params[:order][:postcode]
          @order.address = params[:order][:address]
          @order.name = params[:order][:name]
      end
      @order.save

      unless Delivery.find_by(address: @order.address)
        @delivery = Delivery.new
        @delivery.postcode = @order.postcode
        @delivery.address = @order.address
        @delivery.name = @order.name
        @delivery.client_id = current_client.id
        @delivery.save
      end

      current_client.cart_items.each do |cart_item|
        order_item = @order.order_items.build
        order_item.order_id = @order.id
        order_item.product_id = cart_item.product_id
        order_item.quantity = cart_item.quantity
        order_item.price = cart_item.product.price
        order_item.save
        cart_item.destroy
      end
      render :thanks
    else
      flash[:notice] = "カートが空です！"
      redirect_to root_path
    end
  end

  def confirm
    @order = Order.new
    @cart_items = current_client.cart_items
    @order.pay_method = params[:order][:pay_method]
    @order.billed_amount = params[:order][:billed_amount]
    @add = params[:order][:add].to_i
    case @add
      when 1
        @order.postcode = @client.postcode
        @order.address = @client.address
        @order.name = "#{@client.last_name} #{@client.first_name}"
      when 2
        @address = params[:order][:address].to_i
        @delivery = Delivery.find(@address)
        @order.postcode = @delivery.postcode
        @order.address = @delivery.address
        @order.name = @delivery.name
      when 3
        @order.postcode = params[:order][:new_add][:postcode]
        @order.address = params[:order][:new_add][:address]
        @order.name = params[:order][:new_add][:name]
    end
  end

  def thanks
  end

  def index
    @orders = @client.orders.order(id: "DESC")
  end

  def show
    @order = Order.find(params[:id])
    if @order.client_id != current_client.id
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def set_client
    @client = current_client
  end

  def order_params
    params.require(:order).permit(
      :address, :name, :status, :pay_method, :postcode, :freight, :billed_amount,
      order_items_attributes: [:order_id, :product_id, :quantity, :price, :production_status]
      )
  end

  def authenticate
    unless client_signed_in?
      redirect_to new_client_session_url
      flash[:notice] = "ここから先はログインが必要です!!"
    end
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/client/orders_helper.rb
module Client::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="row" style="margin-bottom: 20px">
	<h2>注文履歴一覧</h2>
</div>
<div class="row">
	<table style="text-align: center;  font-size: 16px;">
		<thead  style="background-color: #FFF2DF;">
			<tr style="border-bottom: solid 2px gray;">
				<th class="col-lg-2" style="text-align: center;">購入日時</th>
				<th class="col-lg-2" style="text-align: center;">購入者</th>
				<th class="col-lg-2" style="text-align: center;">注文個数</th>
				<th class="col-lg-2" style="text-align: center;">注文ステータス</th>
			</tr>
		</thead>
		<tbody>
			<% @orders.each do |order| %>
			<tr style="border-bottom: solid 2px gray">
				<td>
					<%= link_to admin_order_path(order) do %>
						<%= order.created_at.to_s(:datetime_jp2) %>
					<% end %>
				</td>
				<td><%= order.name %></td>
				<td>
					<% sum_all = 0 %>
					<% order.order_items.each do |order_item| %>
					  <% sum_all += order_item.quantity %>
					<% end %>
					<%= sum_all %>
				</td>
				<td><%= order.status %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
	<%= paginate @orders %>
</div>

app/views/admin/orders/show.html.erb
<div class="row" style="margin-bottom: 20px">
	<h2>注文履歴詳細</h2>
</div>
<div class="row">
	<table  style="font-size: 18px;">
		<tbody>
			<tr>
				<td><strong>購入者</strong></td>
				<td><%= @order.name %></td>
			</tr>
			<tr>
				<td><strong>配送先</strong></td>
				<td>
					〒<%= @order.postcode %> <%= @order.address %><br>
					<%= @order.name %>
				</td>
			</tr>
			<tr>
				<td><strong>支払方法</strong></td>
				<td><%= @order.pay_method %></td>
			</tr>
			<tr>
				<td><strong>注文ステータス</strong></td>
				<td>
					<%= form_with(model: @order, url: admin_order_path, local: true) do |f| %>
						<%= f.select :status, Order.statuses.keys.map {|k| [k, k]} %>
						<%= f.submit '更新', class: 'btn btn-primary' %>
					<% end %>
				</td>
			</tr>
		</tbody>
	</table>
</div>
<div class="row"  style="font-size: 16px; margin: 20px 0;">
	<div class="col-lg-7">
		<table>
			<thead style="border-bottom: solid 2px gray; background-color: #FFF2DF;">
				<tr>
					<th>商品名</th>
					<th>単価(税込)</th>
					<th>数量</th>
					<th>小計</th>
					<th>制作ステータス</th>
				</tr>
			</thead>
			<tbody>
				<% @order_items.each do |order_item| %>
				<tr style="border-bottom: solid 2px gray;">
					<td><%= order_item.product.name %></td>
					<td><%= price_include_tax(order_item.product.price) %></td>
					<td><%= order_item.quantity%></td>
					<td>
						<%= sum_product = price_include_tax(order_item.product.price).to_i * order_item.quantity %>円
					</td>
					<td>
						<%= form_with(model: order_item, url: admin_order_item_path(order_item), local: true) do |f| %>
							<%= f.select :production_status, OrderItem.production_statuses.keys.map {|k| [k, k]} %>
							<%= f.submit '更新', class: 'btn btn-primary' %>
						<% end %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>

	<div class="col-lg-5">
		<table>
			<tbody>
				<tr style="border-bottom: solid 2px gray;">
					<td>商品合計</td>
					<td><%= @order.billed_amount - @order.freight %>円</td>
				</tr>
				<tr style="border-bottom: solid 2px gray;">
					<td>送料</td>
					<td><%= @order.freight %>円</td>
				</tr>
				<tr style="border-bottom: solid 2px gray;">
					<td>請求金額合計</td>
					<td><%=  @order.billed_amount %>円</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>
<div class="row" style="text-align: center; padding-top: 20px;">
	<%= link_to "注文履歴一覧へ戻る", admin_orders_path, class: "btn-lg btn-success" %>
</div>