config/routes.rb
Rails.application.routes.draw do



  resources :cart_items, only: [:index, :create, :update, :destroy] do
     collection do
       delete 'destroy_all'
    end
  end

  resources :deliveries, only: [:index, :create, :edit, :update, :destroy]


  devise_for :admins, controllers: {
    sessions: 'admin/admins/sessions',
    registrations: 'admin/admins/registrations',
    passwords: 'admin/admins/passwords'
  }

  namespace :admin do
  	resources :products, only: [:new, :create, :edit, :update, :show, :index]
  	get 'home/top'
  	root 'home#top'
    get 'search' => 'search#search'
  	resources :orders, only: [:update, :index, :show]
  	resources :order_items, only: [:update]
  	resources :genres, only: [:index, :create, :edit, :update]
    resources :clients, only: [:show, :edit, :update, :index] do
      member do
        get "unsubscribe"
        patch "unsubscribe"
      end
    end
  end

  scope module: :client do
    devise_for :clients, controllers: {
      sessions: 'client/clients/sessions',
      registrations: 'client/clients/registrations',
      passwords: 'client/clients/passwords'
    }
  	resources :products, only: [:index, :show]
  	get 'home/top'
  	root 'home#top'
  	get 'home/about'
  	resources :orders, only: [:new, :create, :index, :show]
  	post 'orders/confirm'
  	get 'orders/thanks'
    get 'products/search/:id' => 'products#search', as: 'products_search'
    resources :clients, only: [:show, :edit, :update] do
      member do
        get "unsubscribe"
        patch "unsubscribe"
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :client
	belongs_to :product
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

  before_action :authenticate

  def create
    @cart_item = CartItem.new(cart_item_params)
    @cart_item.client_id = current_client.id
    @current_item = CartItem.find_by(product_id: @cart_item.product_id, client_id: current_client.id)
    if @current_item.nil?
      if @cart_item.save
        redirect_to cart_items_path
      else
        @cart_items = CartItem.all
        render 'index'
      end
    else
      @current_item.quantity += @cart_item.quantity
      @current_item.save
      redirect_to cart_items_path
    end
  end


  def index
    @cart_items = CartItem.all
    @cart_item = CartItem.new
  end


  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(cart_item_params)
    redirect_to cart_items_path
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to cart_items_path
  end

  def destroy_all
    if current_client.cart_items.destroy_all
      flash[:notice] = 'カートを空にしました。'
      redirect_to cart_items_path
    end
  end


  private

  def cart_item_params
    params.require(:cart_item).permit(:product_id, :quantity)
  end

  def authenticate
    unless client_signed_in?
      redirect_to new_client_session_url
      flash[:notice] = "ここから先はログインが必要です!!"
    end
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/index.html.erb
<div class="container">
	<div class="row">
      <div class="col-mt-1">
      	<h2>ショッピングカート</h2>
  　　　　<div class="text-right">
    　　　　<%= link_to 'カートを空にする', destroy_all_cart_items_path, method: :delete, class: "btn btn-danger btn-xs" %>
  　　　　</div>

　　　　　　<table class="table table-bordered">
	　　　　　<thead>
	　　　　　	<tr>
			　　　<th>商品名</th>
		　　　　　	<th style="width:15%">単価（税込）</th>
		　　　　　	<th style="width:15%">数量</th>
		　　　　　	<th>小計</th>
			　　　　　<th colspan=""></th>
		　　　　　</tr>
	　　　　　</thead>
　　         <% sum_all = 0 %>
	         <% @cart_items.each do |cart_item| %>
	         <tbody>
	        	<tr style="border-bottom: solid 2px gray">
	        		<td>
					    <%= attachment_image_tag(cart_item.product, :image, :fill, 60, 60) %>
					    <%= cart_item.product.name %>
				    </td>
			        <td>
			        	<%= price_tax(cart_item.product.price).to_s(:delimited) %>

			        </td>
			        <td>
					    <%= form_with model: cart_item, local: true do |f| %>
					    <%= f.number_field :quantity, value: cart_item.quantity, min:1, max:99 %>
					    <%= f.submit "変更", class: "btn btn-primary btn-xs"%>
					　　　<% end %>
	 			    </td>
					<td><% sum_product = price_include_tax(cart_item.product.price ).to_i * cart_item.quantity %>
						<%= sum_product.to_s(:delimited) %>
						<% sum_all += sum_product.to_i %>
					</td>
					<td><%= link_to '削除', cart_item_path(cart_item), method: :delete, class: "btn btn-danger btn-xs" %></td>

				</tr>
			</tbody>
			<% end %>

		</table>


	　　<%= link_to '買い物を続ける', root_path, class: "btn btn-primary btn-sm" %>
	　　<div class="text-right">
		   <p class="h4">合計金額：<%= sum_all.to_s(:delimited) %>円</p>
		</div>
		<div class="text-center">
		 <%= link_to '情報入力に進む', new_order_path, class: "btn btn-success" %>
	    </div>
	</div>
</div>