config/routes.rb
Rails.application.routes.draw do



  resources :cart_items, only: [:index, :create, :update, :destroy] do
     collection do
       delete 'destroy_all'
    end
  end

  resources :deliveries, only: [:index, :create, :edit, :update, :destroy]


  devise_for :admins, controllers: {
    sessions: 'admin/admins/sessions',
    registrations: 'admin/admins/registrations',
    passwords: 'admin/admins/passwords'
  }

  namespace :admin do
  	resources :products, only: [:new, :create, :edit, :update, :show, :index]
  	get 'home/top'
  	root 'home#top'
    get 'search' => 'search#search'
  	resources :orders, only: [:update, :index, :show]
  	resources :order_items, only: [:update]
  	resources :genres, only: [:index, :create, :edit, :update]
    resources :clients, only: [:show, :edit, :update, :index] do
      member do
        get "unsubscribe"
        patch "unsubscribe"
      end
    end
  end

  scope module: :client do
    devise_for :clients, controllers: {
      sessions: 'client/clients/sessions',
      registrations: 'client/clients/registrations',
      passwords: 'client/clients/passwords'
    }
  	resources :products, only: [:index, :show]
  	get 'home/top'
  	root 'home#top'
  	get 'home/about'
  	resources :orders, only: [:new, :create, :index, :show]
  	post 'orders/confirm'
  	get 'orders/thanks'
    get 'products/search/:id' => 'products#search', as: 'products_search'
    resources :clients, only: [:show, :edit, :update] do
      member do
        get "unsubscribe"
        patch "unsubscribe"
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/search_controller.rb
class Admin::SearchController < ApplicationController

  before_action :authenticate_admin!

	def search
	  @model = params[:model]
	  search = params[:search]
	  word = params[:word]
		if @model == 'client'
			@client = Client.search(search,word)
		else
			@product = Product.search(search,word)
		end
	end

end

app/helpers/admin/search_helper.rb
module Admin::SearchHelper
end

app/views/admin/search/search.html.erb
<h2>検索結果</h2>

<% if @model == 'client' %>

<div class="container">
  <div class="row">
      <div class="col-xs-1">
      </div>
      <div class="col-xs-9">
       <table class="api-table">
      <thead>
        <tr>
          <th class="api-th">会員ID</th>
          <th class="api-th">氏名</th>
          <th class="api-th">メールアドレス</th>
          <th class="api-th">ステータス</th>
        </tr>
      </thead>
      <% @client.each do |client| %>
        <tbody>
          <tr>
            <td class="api-td"><%= client.id %></td>
            <td class="api-td"><%= link_to admin_client_path(client) do %>
                <%= client.last_name %><%= client.first_name %>
                <% end %></td>
            <td class="api-td"><%= client.email %></td>
            <td class="api-td"><% if client.is_deleted == true %>退会済み
                <% else %>有効
                <% end %></td>
          </tr>
        </tbody>
      <% end %>
    </table>
  </div>

</div>

<% end %>

<% if @model == 'product' %>
<div class="container">
  <div class="row">
    <div class="col-xs-1">
    </div>
    <div class="col-xs-9">
        <table class="api-table">
          <thead>
            <tr>
              <th class="api-th">商品ID</th>
              <th class="api-th">商品名</th>
              <th class="api-th">税抜価格</th>
              <th class="api-th">ジャンル</th>
              <th class="api-th">販売ステータス</th>
            </tr>
          </thead>

          <tbody>
            <% @product.each do |product| %>
              <tr>
                <td class="api-td"><%= product.id %></td>
                <td class="api-td"><%= link_to  product.name.truncate(15), admin_product_path(product) %></td>
                <td class="api-td"><%= product.price.to_s(:delimited) %></td>
                <td class="api-td"><%= product.genre.name %></td>
                <td class="api-td"><% if product.sale_status == true %>販売中
                    <% else %>売り切れ
                    <% end %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
    <div class="col-xs-2">
    </div>
  </div>
</div>
<% end %>